[package]
name = "persistent_rope"
version = "0.1.0"
authors = ["Michael Dunsmuir <mjdunsmuir@gmail.com>"]
publish = false

[features]

lint = ["clippy"]

[dependencies]
clippy = { version = "*", optional = true }
